name: "Step 1: Prep Release"
on:
  workflow_dispatch:
    inputs:
      version_spec:
        description: "New Version Specifier"
        default: "next"
        required: false
      branch:
        description: "The branch to target"
        required: false
      since:
        description: "Use PRs with activity since this date or git reference"
        required: false
      since_last_stable:
        description: "Use PRs with activity since the last stable git tag"
        required: false
        type: boolean
jobs:
  call_prep_release:
    uses: MAAP-Project/algorithms-jupyter-extension/.github/workflows/prep-release.yml@develop
    secrets: inherit
    with:
      version_spec: "${{ github.event.inputs.version_spec }}"
      branch: "${{ github.event.inputs.branch }}"
      since: "${{ github.event.inputs.since }}"
      since_last_stable: ${{ fromJSON(github.event.inputs.since_last_stable) }}
